---
- name: Install apps
  host: localhost

  tasks:
  - name: Download necessary packages
    ansible.builtin.package:
      name:
        - tmux
        - zsh
        - fzf
        - git
        - wget
        - curl
      state: present
    become: true
